### ISSUE TITLE
Create function prev in TimeSeriesModule

### ISSUE THREAD

**Issue by wenta** [carldata/flow-script#143]
- finds the previous value in the provided timeseries

**Comment by wenta** [comment]
What value should be in first element? Maybe first index should be deleted?

**Comment by klangner** [comment]
First element should be delete. It will work as tail()

**Comment by wenta** [comment]
Ok.

**Comment by klangner** [comment]
Just to be sure.
If we have series like this
ts = TimeSeries((1, 1), (2, 2), (3,3))

then prev(ts) should be
(2, 1), (3,2)
