### ISSUE TITLE
Implement TimeSeries functions

### ISSUE THREAD

**Issue by klangner** [carldata/flow-script#57]
* [x] - running_total
  * [x] - differentiate
  * [x] - diff_time (delta)
  * [x] - discrete
  * [x] - fill_missing
  * [x] - interpolate
  * [x] - manning_flow
  * [x] - manning_velocity
  * [x] - maximum
  * [x] - median
  * [x] - minimum
  * [x] - periodic constant
  * [x] - repeat
  * [x] - rolling_avg
  * [x] - rolling_sum
  * [x] - shift
  * [x] - step
  * [x] - sum
  * [x] - time_weighted_avg

**Comment by wenta** [comment]
I will take 'running_total'.

**Comment by klangner** [comment]
Sorry. It is done :-)
